[2024-04-16T09:41:57.155+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:41:57.173+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:26:00+00:00 [queued]>
[2024-04-16T09:41:57.180+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:26:00+00:00 [queued]>
[2024-04-16T09:41:57.180+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T09:41:57.193+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 06:26:00+00:00
[2024-04-16T09:41:57.200+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3517) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:41:57.202+0000] {standard_task_runner.py:63} INFO - Started process 3534 to run task
[2024-04-16T09:41:57.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T06:26:00+00:00', '--job-id', '892', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1ks8w51v']
[2024-04-16T09:41:57.203+0000] {standard_task_runner.py:91} INFO - Job 892: Subtask hello2
[2024-04-16T09:41:57.238+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:26:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:41:57.311+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:26:00+00:00'
[2024-04-16T09:41:57.312+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:42:00.872+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-16T09:42:04.149+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-16T09:42:04.151+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:42:04.152+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 98, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 11, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-16T09:42:04.160+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T062600, start_date=20240416T094157, end_date=20240416T094204
[2024-04-16T09:42:04.170+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 892 for task hello2 ('NoneType' object is not subscriptable; 3534)
[2024-04-16T09:42:04.191+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T09:42:04.203+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:42:04.205+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-16T09:48:48.818+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:48:48.850+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:26:00+00:00 [queued]>
[2024-04-16T09:48:48.864+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:26:00+00:00 [queued]>
[2024-04-16T09:48:48.865+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T09:48:48.882+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 06:26:00+00:00
[2024-04-16T09:48:48.894+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4967) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:48:48.896+0000] {standard_task_runner.py:63} INFO - Started process 4995 to run task
[2024-04-16T09:48:48.897+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T06:26:00+00:00', '--job-id', '1343', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4zqfh4kj']
[2024-04-16T09:48:48.899+0000] {standard_task_runner.py:91} INFO - Job 1343: Subtask hello2
[2024-04-16T09:48:48.961+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:26:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:48:49.088+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:26:00+00:00'
[2024-04-16T09:48:49.092+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:48:49.596+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:50.028+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:50.428+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:50.434+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:50.435+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:50.448+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:50.449+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:50.450+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:50.451+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:50.452+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T09:48:50.452+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:48:50.460+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T062600, start_date=20240416T094848, end_date=20240416T094850
[2024-04-16T09:48:50.521+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T09:48:50.534+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:48:50.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
