[2024-04-16T09:41:55.385+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:41:55.411+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:16:00+00:00 [queued]>
[2024-04-16T09:41:55.424+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:16:00+00:00 [queued]>
[2024-04-16T09:41:55.425+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T09:41:55.448+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 06:16:00+00:00
[2024-04-16T09:41:55.461+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3482) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:41:55.463+0000] {standard_task_runner.py:63} INFO - Started process 3515 to run task
[2024-04-16T09:41:55.468+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T06:16:00+00:00', '--job-id', '881', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpo6yib884']
[2024-04-16T09:41:55.470+0000] {standard_task_runner.py:91} INFO - Job 881: Subtask hello2
[2024-04-16T09:41:55.548+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:16:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:41:55.692+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:16:00+00:00'
[2024-04-16T09:41:55.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:41:59.263+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-16T09:42:02.535+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-16T09:42:02.536+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:42:02.538+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 98, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 11, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-16T09:42:02.548+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T061600, start_date=20240416T094155, end_date=20240416T094202
[2024-04-16T09:42:02.561+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 881 for task hello2 ('NoneType' object is not subscriptable; 3515)
[2024-04-16T09:42:02.579+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T09:42:02.590+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:42:02.593+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-16T09:48:40.331+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:48:40.347+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:16:00+00:00 [queued]>
[2024-04-16T09:48:40.353+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:16:00+00:00 [queued]>
[2024-04-16T09:48:40.353+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T09:48:40.363+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 06:16:00+00:00
[2024-04-16T09:48:40.370+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4904) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:48:40.371+0000] {standard_task_runner.py:63} INFO - Started process 4916 to run task
[2024-04-16T09:48:40.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T06:16:00+00:00', '--job-id', '1325', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp54pan9v3']
[2024-04-16T09:48:40.372+0000] {standard_task_runner.py:91} INFO - Job 1325: Subtask hello2
[2024-04-16T09:48:40.408+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:16:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:48:40.479+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:16:00+00:00'
[2024-04-16T09:48:40.480+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:48:40.874+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:41.308+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:41.741+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:41.745+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:41.746+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:41.754+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:41.755+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:41.756+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:41.757+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:41.758+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T09:48:41.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:48:41.766+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T061600, start_date=20240416T094840, end_date=20240416T094841
[2024-04-16T09:48:41.789+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T09:48:41.799+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:48:41.801+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
