[2024-04-16T09:41:55.820+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:41:55.852+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:18:00+00:00 [queued]>
[2024-04-16T09:41:55.863+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:18:00+00:00 [queued]>
[2024-04-16T09:41:55.863+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T09:41:55.883+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 06:18:00+00:00
[2024-04-16T09:41:55.895+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3493) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:41:55.898+0000] {standard_task_runner.py:63} INFO - Started process 3519 to run task
[2024-04-16T09:41:55.897+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T06:18:00+00:00', '--job-id', '882', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp28tjjiiv']
[2024-04-16T09:41:55.900+0000] {standard_task_runner.py:91} INFO - Job 882: Subtask hello2
[2024-04-16T09:41:55.961+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:18:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:41:56.132+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:18:00+00:00'
[2024-04-16T09:41:56.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:41:59.744+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-16T09:42:03.014+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-16T09:42:03.016+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:42:03.017+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 98, in processes
    album_data = get_album(connection())
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/get_data.py", line 11, in get_album
    for album in data["items"]:
                 ~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-04-16T09:42:03.025+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T061800, start_date=20240416T094155, end_date=20240416T094203
[2024-04-16T09:42:03.064+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 882 for task hello2 ('NoneType' object is not subscriptable; 3519)
[2024-04-16T09:42:03.096+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T09:42:03.111+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:42:03.113+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-16T09:48:40.496+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T09:48:40.517+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:18:00+00:00 [queued]>
[2024-04-16T09:48:40.527+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:18:00+00:00 [queued]>
[2024-04-16T09:48:40.528+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-16T09:48:40.541+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello2> on 2024-04-16 06:18:00+00:00
[2024-04-16T09:48:40.548+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4906) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T09:48:40.549+0000] {standard_task_runner.py:63} INFO - Started process 4919 to run task
[2024-04-16T09:48:40.550+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello2', 'scheduled__2024-04-16T06:18:00+00:00', '--job-id', '1326', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpaz6xo0f3']
[2024-04-16T09:48:40.550+0000] {standard_task_runner.py:91} INFO - Job 1326: Subtask hello2
[2024-04-16T09:48:40.590+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello2 scheduled__2024-04-16T06:18:00+00:00 [running]> on host 52651c1f9987
[2024-04-16T09:48:40.677+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello2' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T06:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T06:18:00+00:00'
[2024-04-16T09:48:40.679+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T09:48:41.071+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:41.472+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:42.052+0000] {logging_mixin.py:188} INFO - Connection successful
[2024-04-16T09:48:42.056+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:42.057+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:42.066+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:42.066+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:42.067+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:42.068+0000] {logging_mixin.py:188} INFO - Null Not Found
[2024-04-16T09:48:42.069+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-16T09:48:42.069+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T09:48:42.076+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=spotify_final_dag, task_id=hello2, execution_date=20240416T061800, start_date=20240416T094840, end_date=20240416T094842
[2024-04-16T09:48:42.128+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T09:48:42.140+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T09:48:42.142+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
