[2024-04-17T05:20:39.324+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T05:20:39.347+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T10:42:00+00:00 [queued]>
[2024-04-17T05:20:39.356+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T10:42:00+00:00 [queued]>
[2024-04-17T05:20:39.357+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-17T05:20:39.374+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): hello> on 2024-04-16 10:42:00+00:00
[2024-04-17T05:20:39.387+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T05:20:39.389+0000] {standard_task_runner.py:63} INFO - Started process 91 to run task
[2024-04-17T05:20:39.394+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_final_dag', 'hello', 'scheduled__2024-04-16T10:42:00+00:00', '--job-id', '1572', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpd_66hfpg']
[2024-04-17T05:20:39.397+0000] {standard_task_runner.py:91} INFO - Job 1572: Subtask hello
[2024-04-17T05:20:39.479+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_final_dag.hello scheduled__2024-04-16T10:42:00+00:00 [running]> on host 52651c1f9987
[2024-04-17T05:20:39.619+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_final_dag' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T10:42:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T10:42:00+00:00'
[2024-04-17T05:20:39.622+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T05:20:43.356+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 1, Status Code: 401
[2024-04-17T05:20:46.630+0000] {logging_mixin.py:188} INFO - There was a problem with the connection. Trial number 2, Status Code: 401
[2024-04-17T05:20:46.632+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-17T05:20:46.632+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T05:20:46.640+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=spotify_final_dag, task_id=hello, execution_date=20240416T104200, start_date=20240417T052039, end_date=20240417T052046
[2024-04-17T05:20:46.671+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-17T05:20:46.697+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-17T05:20:46.703+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
